using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Android.Support.V7.Widget;

namespace Boodschapp_PO4
{
    public class Product
    {
        public ProductCategory category { get; }

        public ProductGroup group { get; }

        public string name { get; }

        public int image { get; }


        public Product(ProductCategory category = ProductCategory.Other, ProductGroup group = ProductGroup.Other, string name = "Default", int image = 0)
        {
            this.category   = category;
            this.group      = group;
            this.name       = name;
            this.image      = image;
        }
    }

    public class ProductList
    {

        private static Product[] mConfirmedProducts =
            {
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Andijvie"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Broccoli"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Bloemkool"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Spitskool"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Groene kool"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Wortels"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Peulen"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Witlof"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Spinazie"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Uien"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Bosuien"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Bleekselderij"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Paprika"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Komkommer"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Courgette"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Aubergine"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Asperge"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Sla"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Ijsbergsla"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables,
                        name: "Tomaten"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Kaneel"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Keukenzout"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Zeezout"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Witte peper"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Zwarte peper"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Koriander"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Peterselie"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Nootmuskaat"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Laurier"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Basilicum"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Paprikapoeder"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Kerriepoeder"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Italiaanse kruiden"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Gemalen knoflook"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Komijnzaad"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Tijm"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Rozemarijn"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Knoflookpoeder"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Oregano"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Salie"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Uienpoeder"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Spices,
                        name: "Cayennepeper"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Mayonaise"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Curry"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Ketchup"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Barbecuesaus"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Whiskey cocktailsaus"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Knoflooksaus"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Chilisaus"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Mosterd"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Truffelmayonaise"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Pindasaus"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Fritessaus"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Kaassaus"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Aspergesaus"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Hollandaisesaus"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Pepersaus"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Groentesaus"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Kerriesaus"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: "Champignonsaus"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Sauzen,
                        name: ""),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fruits,
                        name: "Aardbeien"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fruits,
                        name: "Watermeloen"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fruits,
                        name: "Meloen"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fruits,
                        name: "Bananen"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fruits,
                        name: "Appels"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fruits,
                        name: "Peren"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fruits,
                        name: "Perziken"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fruits,
                        name: "Abrikozen"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fruits,
                        name: "Citroenen"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fruits,
                        name: "Sinaasappelen"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fruits,
                        name: "Mandarijnen"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fruits,
                        name: "Frambozen"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fruits,
                        name: "Blauwe bessen"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fruits,
                        name: "Mango"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fruits,
                        name: "Avocado"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fruits,
                        name: "Ananas"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Dairy,
                        name: "Yoghurt"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Dairy,
                        name: "Boter"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Dairy,
                        name: "Melk"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Dairy,
                        name: "Kaas"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Dairy,
                        name: "Vla"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Cookies,
                        name: "Stroopkoek"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Cookies,
                        name: "Stroopwafel"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Cookies,
                        name: "Roze koek"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Cookies,
                        name: "Mergpijpen"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Cookies,
                        name: "Bokkenpootjes"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Cookies,
                        name: "Biscuits"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Cookies,
                        name: "Speculaas"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Cookies,
                        name: "Gevulde koek"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Cookies,
                        name: "Boterkoek"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Cookies,
                        name: "Cakejes"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Cookies,
                        name: "Appelkoek"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Cookies,
                        name: "Kletsmajoors"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Cookies,
                        name: ""),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Soup,
                        name: "Groentensoep"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Soup,
                        name: "Tomatensoep"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Soup,
                        name: "Uiensoep"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Soup,
                        name: "Aspergesoep"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Soup,
                        name: "Juliennesoep"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Soup,
                        name: "Vermicellisoep"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Soup,
                        name: "Champignonsoep"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Soup,
                        name: "Ossenstaartsoep"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Soup,
                        name: "Erwtensoep"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Soup,
                        name: "Kippensoep"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Soup,
                        name: "Chinese tomatensoep"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Soup,
                        name: "Noedelsoep"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Soup,
                        name: "Eén-kops-soep"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Broodbeleg,
                        name: "Hagelslag"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Broodbeleg,
                        name: "Chocopasta"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Broodbeleg,
                        name: "Witte chocopasta"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Broodbeleg,
                        name: "Pure hagelslag"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Broodbeleg,
                        name: "Speculoospasta"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Broodbeleg,
                        name: "Honing"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Broodbeleg,
                        name: "Appelstroop"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Broodbeleg,
                        name: "Jam"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Broodbeleg,
                        name: "Sandwich spread"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Broodbeleg,
                        name: "Schuddebuikjes"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Broodbeleg,
                        name: "Vlokken"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Broodbeleg,
                        name: "Anijshagel"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Broodbeleg,
                        name: "Pindakaas"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Broodbeleg,
                        name: "Vruchtenhagel"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Pannenkoekenmix"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Poffertjesmix"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Pizzabodem mix"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Mix voor muffins"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Mix voor kwarktaart"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Mix voor monchou"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Broodmix"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Appeltaart mix"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Mix voor brownies"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Mix voor chocoladetaart"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Mix voor velvet cake"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Mix voor boerencake"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Mix voor cake"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Bloem"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Paneermeel"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Taartdecoratie"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Taartbodem"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Baking,
                        name: "Mix voor cupcakes"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Borrelnootjes"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Toastjes"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Kaaskoekjes"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Zoute pepsels"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Pindapepsels"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Kaasstengels"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Cashewnoten ongezouten"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Cashewnoten gezouten"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Pinda's gezouten"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Pinda's ongezouten"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Shanghainoten"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Pistachenoten"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Studentenhaver"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Elitehaver"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Chips bolognese"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Chips naturel"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Chips paprika"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Chips barbecue"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Chips ham/kaas"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Chips zeezout"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Groentechips"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Snacks,
                        name: "Nacho chips"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Confections,
                        name: "Drop"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Confections,
                        name: "Chocolade"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Confections,
                        name: "Toffee"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Confections,
                        name: "Kauwgom"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Confections,
                        name: "Pepermunt"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Confections,
                        name: "Winegums"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Confections,
                        name: "Keelsnoepjes"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Meat,
                        name: "Speklap"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Meat,
                        name: "Schnitzel"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Meat,
                        name: "Hamburger"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Meat,
                        name: "Gehakt"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Meat,
                        name: "Schnitzel"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Meat,
                        name: "Kippenpoot"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Meat,
                        name: "Kipfilet"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Meat,
                        name: "Zalm"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fish,
                        name: "Forel"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fish,
                        name: "Haring"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fish,
                        name: "Kibbeling"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Fish,
                        name: "Markreel"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Canned,
                        name: "Witte bonen"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Canned,
                        name: "Bruine bonen"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Canned,
                        name: "Spinazie"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Canned,
                        name: "Sperziebonen"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Canned,
                        name: "Boerenkool"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Canned,
                        name: "Erwten"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Canned,
                        name: "Wortels"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Canned,
                        name: "Mais"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Canned,
                        name: "Rode kool"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Canned,
                        name: "Bieten"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Canned,
                        name: "Tuinbonen"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Soda,
                        name: "Cola"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Soda,
                        name: "Sinas"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Soda,
                        name: "Tonic"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Soda,
                        name: "Cassis"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Soda,
                        name: "Ijsthee"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Soda,
                        name: "Energiedrank"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Alcohol,
                        name: "Bier"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Alcohol,
                        name: "Vodka"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Alcohol,
                        name: "Witte wijn"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Alcohol,
                        name: "Rum"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Alcohol,
                        name: "Jägermeister"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Alcohol,
                        name: "Bacardi/cola"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Alcohol,
                        name: "Likeur"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Alcohol,
                        name: "Jenever"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Alcohol,
                        name: "Rosé"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Alcohol,
                        name: "Rode wijn"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Caffinated,
                        name: "Roodfilter"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Caffinated,
                        name: "Caffeïnevrij"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Caffinated,
                        name: "Koffiepads normaal"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Caffinated,
                        name: "Koffiepads sterk"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Caffinated,
                        name: "Koffiepads extra sterk"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Caffinated,
                        name: "Koffiebonen"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Caffinated,
                        name: "Cappuchino"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Caffinated,
                        name: "Latte macchiato"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Caffinated,
                        name: "Espresso"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Volle melk"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Halfvolle melk"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Magere melk"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Chocolademelk vol"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Chocolademelk mager"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Chocolademelk halfvol"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Yoghurtdrink aardbei"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Yoghurtdrink perzik"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Fristi"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Sojamelk"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Amandelmelk"),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Rijstmelk"),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Confections ),
            new Product( category: ProductCategory.Food,
                        group: ProductGroup.Vegetables ),

            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Alcohol,
                        image: Resource.Drawable.DrinkItemsAsset),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Dairy,
                        image: Resource.Drawable.DrinkItemsAsset),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Caffinated,
                        image: Resource.Drawable.DrinkItemsAsset),
            new Product( category: ProductCategory.Drinks,
                        group: ProductGroup.Soda,
                        image: Resource.Drawable.DrinkItemsAsset),

            new Product( category: ProductCategory.Dishes,
                        group: ProductGroup.Pancakes,
                        image: Resource.Drawable.DishItemsAsset),
            new Product( category: ProductCategory.Dishes,
                        group: ProductGroup.Waffles,
                        image: Resource.Drawable.DishItemsAsset),
            new Product( category: ProductCategory.Dishes,
                        group: ProductGroup.Pizza,
                        image: Resource.Drawable.DishItemsAsset),
            new Product( category: ProductCategory.Dishes,
                        group: ProductGroup.Omelet,
                        image: Resource.Drawable.DishItemsAsset),

            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Cosmetics,
                        image: Resource.Drawable.BathroomItemsAsset),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Bathroom,
                        image: Resource.Drawable.BathroomItemsAsset),
            };


        private List<Product> mProducts;


        public ProductList()
        {
            mProducts = new List<Product>();
            mProducts.Add(new Product(ProductCategory.Food));
            int counter;

            counter = 0;

            for (int i = 0; i < mConfirmedProducts.Length; i++)
            {
                for (int j = 0; j < mProducts.Count; j++)
                {
                    if (mProducts[j].category != mConfirmedProducts[i].category)
                    {
                        counter += 1;
                    }

                    if (counter == mProducts.Count)
                    {
                        mProducts.Add(mConfirmedProducts[i]);
                    }
                }

                counter = 0;
            }
        }


        public ProductList(ProductCategory CategoryID)
        {
            mProducts = new List<Product>();

            for (int i = 0; i < mConfirmedProducts.Length; i++)
            {
                if (mConfirmedProducts[i].category == CategoryID)
                {
                    mProducts.Add(mConfirmedProducts[i]);
                }
            }
        }

        public ProductList(ProductCategory CategoryID, ProductGroup GroupID)
        {
            mProducts = new List<Product>();

            for (int i = 0; i < mConfirmedProducts.Length; i++)
            {
                if (mConfirmedProducts[i].group == GroupID)
                {
                    mProducts.Add(mConfirmedProducts[i]);
                }
            }
        }

        public int NumProducts
        {
            get { return mProducts.Count; }
        }

        public Product this[int i]
        {
            get { return mProducts[i]; }
        }

    }
}