using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Android.Support.V7.Widget;

namespace Boodschapp_PO4
{
    public class Product
    {
        public ProductCategory category { get; }

        public ProductGroup group { get; }

        public string name { get; }

        public int image { get; }


        public Product(ProductCategory category = ProductCategory.Other, ProductGroup group = ProductGroup.Other, string name = "Default", int image = 0)
        {
            this.category   = category;
            this.group      = group;
            this.name       = name;
            this.image      = image;
        }
    }

    public class ProductList
    {

        private static Product[] mConfirmedProducts =
            {
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Andijvie"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Broccoli"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Bloemkool"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Spitskool"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Groene kool"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Wortels"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Peulen"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Witlof"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Spinazie"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Uien"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Bosuien"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Bleekselderij"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Paprika"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Komkommer"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Courgette"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Aubergine"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Asperge"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Sla"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Ijsbergsla"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente,
                        name: "Tomaten"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Pizza Mozzarella"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Pizza Funghi"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Pizza Tonno"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Pizza Hawaii"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Pizza Margherita"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Pizza Salami"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Waterijs"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Vanille ijs"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Aardbeien ijs"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Chocolade ijs"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Cornetto's"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Vienetta"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Soesjes"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Soepgroenten"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Frikandellen"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Kroketten"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Kaassoufflé"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Loempia's"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Bitterballen"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Bamihapjes"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Hamburgers"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Diepvries,
                        name: "Kipnuggets"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Kaneel"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Keukenzout"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Zeezout"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Witte peper"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Zwarte peper"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Koriander"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Peterselie"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Nootmuskaat"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Laurier"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Basilicum"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Paprikapoeder"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Kerriepoeder"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Italiaanse kruiden"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Gemalen knoflook"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Komijnzaad"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Tijm"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Rozemarijn"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Knoflookpoeder"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Oregano"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Salie"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Uienpoeder"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kruiden,
                        name: "Cayennepeper"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Mayonaise"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Curry"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Ketchup"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Barbecuesaus"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Whiskey cocktailsaus"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Knoflooksaus"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Chilisaus"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Mosterd"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Truffelmayonaise"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Pindasaus"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Fritessaus"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Kaassaus"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Aspergesaus"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Hollandaisesaus"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Pepersaus"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Groentesaus"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Kerriesaus"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: "Champignonsaus"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Sauzen,
                        name: ""),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Fruit,
                        name: "Aardbeien"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Fruit,
                        name: "Watermeloen"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Fruit,
                        name: "Meloen"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Fruit,
                        name: "Bananen"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Fruit,
                        name: "Appels"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Fruit,
                        name: "Peren"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Fruit,
                        name: "Perziken"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Fruit,
                        name: "Abrikozen"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Fruit,
                        name: "Citroenen"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Fruit,
                        name: "Sinaasappelen"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Fruit,
                        name: "Mandarijnen"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Fruit,
                        name: "Frambozen"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Fruit,
                        name: "Blauwe bessen"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Fruit,
                        name: "Mango"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Fruit,
                        name: "Avocado"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Fruit,
                        name: "Ananas"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Ontbijt,
                        name: "Havermout"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Ontbijt,
                        name: "Cornflakes"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Ontbijt,
                        name: "Brinta"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Ontbijt,
                        name: "Ontbijtkoek"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Ontbijt,
                        name: "Rijstwafels"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Ontbijt,
                        name: "Crackers"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Ontbijt,
                        name: "Beschuit"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Ontbijt,
                        name: "Kaiserbroodjes"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Ontbijt,
                        name: "Pistolets"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Ontbijt,
                        name: "Croissants"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Ontbijt,
                        name: "Ciabatta"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Ontbijt,
                        name: "Meergranenbrood"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Ontbijt,
                        name: "Tarwebrood"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Ontbijt,
                        name: "Witbrood"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Ontbijt,
                        name: "Panini's"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kaas,
                        name: "Jonge kaas"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kaas,
                        name: "Jong belegen kaas"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kaas,
                        name: "Belegen kaas"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kaas,
                        name: "Oude kaas"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kaas,
                        name: "Schimmelkaas"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kaas,
                        name: "Overjarige kaas"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kaas,
                        name: "Geitenkaas"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Kaas,
                        name: "Geraspte kaas"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Zuivel,
                        name: "Yoghurt"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Zuivel,
                        name: "Drinkyoghurt"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Zuivel,
                        name: "Karnemelk"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Zuivel,
                        name: "Griekse yoghurt"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Zuivel,
                        name: "Yoghurt"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Zuivel,
                        name: "Slagroom"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Zuivel,
                        name: "Boter"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Zuivel,
                        name: "Melk"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Zuivel,
                        name: "Kaas"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Zuivel,
                        name: "Vla"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Koek,
                        name: "Stroopkoek"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Koek,
                        name: "Stroopwafel"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Koek,
                        name: "Roze koek"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Koek,
                        name: "Mergpijpen"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Koek,
                        name: "Bokkenpootjes"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Koek,
                        name: "Biscuits"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Koek,
                        name: "Speculaas"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Koek,
                        name: "Gevulde koek"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Koek,
                        name: "Boterkoek"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Koek,
                        name: "Cakejes"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Koek,
                        name: "Appelkoek"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Koek,
                        name: "Kletsmajoors"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Koek,
                        name: "Granenbiscuit"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Koek,
                        name: "Fruitbiscuit"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Koek,
                        name: "Liga"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Koek,
                        name: "Mueslireep"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Soep,
                        name: "Groentensoep"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Soep,
                        name: "Tomatensoep"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Soep,
                        name: "Uiensoep"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Soep,
                        name: "Aspergesoep"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Soep,
                        name: "Juliennesoep"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Soep,
                        name: "Vermicellisoep"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Soep,
                        name: "Champignonsoep"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Soep,
                        name: "Ossenstaartsoep"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Soep,
                        name: "Erwtensoep"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Soep,
                        name: "Kippensoep"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Soep,
                        name: "Chinese tomatensoep"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Soep,
                        name: "Noedelsoep"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Soep,
                        name: "Eén-kops-soep"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Broodbeleg,
                        name: "Hagelslag"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Broodbeleg,
                        name: "Chocopasta"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Broodbeleg,
                        name: "Witte chocopasta"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Broodbeleg,
                        name: "Pure hagelslag"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Broodbeleg,
                        name: "Speculoospasta"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Broodbeleg,
                        name: "Honing"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Broodbeleg,
                        name: "Appelstroop"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Broodbeleg,
                        name: "Jam"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Broodbeleg,
                        name: "Sandwich spread"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Broodbeleg,
                        name: "Schuddebuikjes"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Broodbeleg,
                        name: "Vlokken"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Broodbeleg,
                        name: "Anijshagel"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Broodbeleg,
                        name: "Pindakaas"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Broodbeleg,
                        name: "Vruchtenhagel"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Broodbeleg,
                        name: "Smeerkaas"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Pannenkoekenmix"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Poffertjesmix"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Pizzabodem mix"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Mix voor muffins"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Mix voor kwarktaart"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Mix voor monchou"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Broodmix"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Appeltaart mix"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Mix voor brownies"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Mix voor chocoladetaart"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Mix voor velvet cake"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Mix voor boerencake"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Mix voor cake"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Bloem"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Paneermeel"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Taartdecoratie"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Taartbodem"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Bakproducten,
                        name: "Mix voor cupcakes"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Pasta,
                        name: "Pastasaus bolognese"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Pasta,
                        name: "Pastasaus pittig"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Pasta,
                        name: "Pastasaus carbonara"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Pasta,
                        name: "Ravioli"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Pasta,
                        name: "Spaghetti"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Pasta,
                        name: "Penne"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Pasta,
                        name: "Tagliatelle"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Pasta,
                        name: "Tortellini"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Pasta,
                        name: "Farfalle"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Pasta,
                        name: "Macaroni"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Pasta,
                        name: "Fusilli"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Rijst,
                        name: "Witte rijst"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Rijst,
                        name: "Notenrijst"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Rijst,
                        name: "Basmati rijst"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Rijst,
                        name: "Pandan rijst"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Rijst,
                        name: "Zilvervlies rijst"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Rijst,
                        name: "Snelkookrijst"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Rijst,
                        name: "Couscous"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Borrelnootjes"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Toastjes"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Kaaskoekjes"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Zoute pepsels"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Pindapepsels"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Kaasstengels"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Cashewnoten ongezouten"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Cashewnoten gezouten"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Pinda's gezouten"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Pinda's ongezouten"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Shanghainoten"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Pistachenoten"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Studentenhaver"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Elitehaver"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Chips bolognese"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Chips naturel"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Chips paprika"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Chips barbecue"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Chips ham/kaas"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Chips zeezout"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Groentechips"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snacks,
                        name: "Nacho chips"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snoep,
                        name: "Drop"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snoep,
                        name: "Chocolade"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snoep,
                        name: "Toffee"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snoep,
                        name: "Kauwgom"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snoep,
                        name: "Pepermunt"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snoep,
                        name: "Winegums"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snoep,
                        name: "Keelsnoepjes"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Vlees,
                        name: "Speklap"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Vlees,
                        name: "Schnitzel"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Vlees,
                        name: "Hamburger"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Vlees,
                        name: "Gehakt"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Vlees,
                        name: "Schnitzel"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Vlees,
                        name: "Kippenpoot"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Vlees,
                        name: "Kipfilet"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Vlees,
                        name: "Zalm"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Vis,
                        name: "Forel"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Vis,
                        name: "Haring"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Vis,
                        name: "Kibbeling"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Vis,
                        name: "Markreel"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Blik,
                        name: "Witte bonen"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Blik,
                        name: "Bruine bonen"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Blik,
                        name: "Spinazie"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Blik,
                        name: "Sperziebonen"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Blik,
                        name: "Boerenkool"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Blik,
                        name: "Erwten"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Blik,
                        name: "Wortels"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Blik,
                        name: "Mais"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Blik,
                        name: "Rode kool"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Blik,
                        name: "Bieten"),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Blik,
                        name: "Tuinbonen"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Sappen,
                        name: "Appelsap"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Sappen,
                        name: "Perensap"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Sappen,
                        name: "Druivensap"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Sappen,
                        name: "Multifruit"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Sappen,
                        name: "Ananassap"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Sappen,
                        name: "Mangosap"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Sappen,
                        name: "Tomatensap"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Sappen,
                        name: "Tintelfruit"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Sappen,
                        name: "Pakjes voor school"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Sappen,
                        name: "Limonadesiroop"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Sappen,
                        name: "Sinaasappelsap"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Frisdrank,
                        name: "Cola"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Frisdrank,
                        name: "Sinas"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Frisdrank,
                        name: "Tonic"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Frisdrank,
                        name: "Cassis"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Frisdrank,
                        name: "Ijsthee"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Frisdrank,
                        name: "Energiedrank"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Alcohol,
                        name: "Bier"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Alcohol,
                        name: "Vodka"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Alcohol,
                        name: "Witte wijn"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Alcohol,
                        name: "Rum"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Alcohol,
                        name: "Jägermeister"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Alcohol,
                        name: "Bacardi/cola"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Alcohol,
                        name: "Likeur"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Alcohol,
                        name: "Jenever"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Alcohol,
                        name: "Rosé"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Alcohol,
                        name: "Rode wijn"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Koffie,
                        name: "Roodfilter"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Koffie,
                        name: "Caffeïnevrij"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Koffie,
                        name: "Koffiepads normaal"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Koffie,
                        name: "Koffiepads sterk"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Koffie,
                        name: "Koffiepads extra sterk"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Koffie,
                        name: "Koffiebonen"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Koffie,
                        name: "Cappuchino"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Koffie,
                        name: "Latte macchiato"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Koffie,
                        name: "Espresso"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Volle melk"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Halfvolle melk"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Magere melk"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Chocolademelk vol"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Chocolademelk mager"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Chocolademelk halfvol"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Yoghurtdrink aardbei"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Yoghurtdrink perzik"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Fristi"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Sojamelk"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Amandelmelk"),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Houdbaarmelk,
                        name: "Rijstmelk"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Dierenvoeding,
                        name: "Hondenbrokken"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Dierenvoeding,
                        name: "Kattenbrokken in saus"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Dierenvoeding,
                        name: "Kattenbrokken in gelei"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Dierenvoeding,
                        name: "Duivenvoer"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Dierenvoeding,
                        name: "Konijnenvoer"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Dierenvoeding,
                        name: "Vissenvoer"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Reinigingsmiddelen,
                        name: "Toiletontstopper"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Reinigingsmiddelen,
                        name: "Afwasmiddel"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Reinigingsmiddelen,
                        name: "Vaatwaszout"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Reinigingsmiddelen,
                        name: "Groene zeep"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Reinigingsmiddelen,
                        name: "Chloor"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Reinigingsmiddelen,
                        name: "Bleekmiddel"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Reinigingsmiddelen,
                        name: "Spiritus"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Reinigingsmiddelen,
                        name: "Ammonia"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Reinigingsmiddelen,
                        name: "Schoonmaakazijn"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Reinigingsmiddelen,
                        name: "Demiwater"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Reinigingsmiddelen,
                        name: "Afvalzakken"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Reinigingsmiddelen,
                        name: "Afwasborstel"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Reinigingsmiddelen,
                        name: "Terpetine"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Wasmiddelen,
                        name: "Wasmiddel kleur"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Wasmiddelen,
                        name: "Wasmiddel wit"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Wasmiddelen,
                        name: "Wasmiddel zwart"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Wasmiddelen,
                        name: "Wasverzachter"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Wasmiddelen,
                        name: "Waspoeder"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Wasmiddelen,
                        name: "Biotex"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Cosmetica,
                        name: "Deodorant roller"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Cosmetica,
                        name: "Deodorant spuit"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Cosmetica,
                        name: "Shampoo mannen"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Cosmetica,
                        name: "Shampoo vrouwen"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Cosmetica,
                        name: "Douchegel"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Cosmetica,
                        name: "Haarspray"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Cosmetica,
                        name: "Haargel"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Cosmetica,
                        name: "Watten"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Cosmetica,
                        name: "Make-up remover"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Kinderen,
                        name: "Babyvoeding"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Cosmetica,
                        name: "Luiers"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Cosmetica,
                        name: "Melkpoeder"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Cosmetica,
                        name: "Ontbijtgranenmix"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Cosmetica,
                        name: "Kindersiroop"),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Cosmetica,
                        name: "Babytoetjes"),

            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Cosmetica,
                        name: ""),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Snoep ),
            new Product( category: ProductCategory.Eten,
                        group: ProductGroup.Groente ),

            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Alcohol,
                        image: Resource.Drawable.DrinkItemsAsset),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Zuivel,
                        image: Resource.Drawable.DrinkItemsAsset),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Koffie,
                        image: Resource.Drawable.DrinkItemsAsset),
            new Product( category: ProductCategory.Drinken,
                        group: ProductGroup.Frisdrank,
                        image: Resource.Drawable.DrinkItemsAsset),

            new Product( category: ProductCategory.Recepten,
                        group: ProductGroup.Pannenkoeken,
                        image: Resource.Drawable.DishItemsAsset),

            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Cosmetica,
                        image: Resource.Drawable.BathroomItemsAsset),
            new Product( category: ProductCategory.Nonfood,
                        group: ProductGroup.Wasmiddelen,
                        image: Resource.Drawable.BathroomItemsAsset),
            };


        private List<Product> mProducts;


        public ProductList()
        {
            mProducts = new List<Product>();
            mProducts.Add(new Product(ProductCategory.Eten));
            int counter;

            counter = 0;

            for (int i = 0; i < mConfirmedProducts.Length; i++)
            {
                for (int j = 0; j < mProducts.Count; j++)
                {
                    if (mProducts[j].category != mConfirmedProducts[i].category)
                    {
                        counter += 1;
                    }

                    if (counter == mProducts.Count)
                    {
                        mProducts.Add(mConfirmedProducts[i]);
                    }
                }

                counter = 0;
            }
        }


        public ProductList(ProductCategory CategoryID)
        {
            mProducts = new List<Product>();

            for (int i = 0; i < mConfirmedProducts.Length; i++)
            {
                if (mConfirmedProducts[i].category == CategoryID)
                {
                    mProducts.Add(mConfirmedProducts[i]);
                }
            }
        }

        public ProductList(ProductCategory CategoryID, ProductGroup GroupID)
        {
            mProducts = new List<Product>();

            for (int i = 0; i < mConfirmedProducts.Length; i++)
            {
                if (mConfirmedProducts[i].group == GroupID)
                {
                    mProducts.Add(mConfirmedProducts[i]);
                }
            }
        }

        public int NumProducts
        {
            get { return mProducts.Count; }
        }

        public Product this[int i]
        {
            get { return mProducts[i]; }
        }

    }
}